### ISSUE TITLE
Internal Error with notifications

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDB#212]
I am getting the following error when I try to view my notifications at https://bugsigdb.org/Special:Notifications: 

# Internal error

```
[251742581bf419b8b60ddc96] /Special:Notifications TypeError from line 567 of /var/www/mediawiki/w/extensions/Echo/includes/formatters/EventPresentationModel.php: Argument 1 passed to EchoEventPresentationModel::getTruncatedTitleText() must be an instance of Title, null given, called in /var/www/mediawiki/w/extensions/Echo/includes/formatters/WatchlistChangePresentationModel.php on line 31

Backtrace:

#0 /var/www/mediawiki/w/extensions/Echo/includes/formatters/WatchlistChangePresentationModel.php(31): EchoEventPresentationModel->getTruncatedTitleText()
#1 /var/www/mediawiki/w/extensions/Echo/includes/formatters/SpecialNotificationsFormatter.php(45): EchoWatchlistChangePresentationModel->getHeaderMessage()
#2 /var/www/mediawiki/w/extensions/Echo/includes/formatters/EchoEventFormatter.php(72): SpecialNotificationsFormatter->formatModel()
#3 /var/www/mediawiki/w/extensions/Echo/includes/DataOutputFormatter.php(189): EchoEventFormatter->format()
#4 /var/www/mediawiki/w/extensions/Echo/includes/DataOutputFormatter.php(149): EchoDataOutputFormatter::formatNotification()
#5 /var/www/mediawiki/w/extensions/Echo/includes/special/SpecialNotifications.php(61): EchoDataOutputFormatter::formatOutput()
#6 /var/www/mediawiki/w/includes/specialpage/SpecialPage.php(600): SpecialNotifications->execute()
#7 /var/www/mediawiki/w/includes/specialpage/SpecialPageFactory.php(640): SpecialPage->run()
#8 /var/www/mediawiki/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#9 /var/www/mediawiki/w/includes/MediaWiki.php(947): MediaWiki->performRequest()
#10 /var/www/mediawiki/w/includes/MediaWiki.php(547): MediaWiki->main()
#11 /var/www/mediawiki/w/index.php(53): MediaWiki->run()
#12 /var/www/mediawiki/w/index.php(46): wfIndexMain()
#13 {main}
```

Here is a video demonstrating how I get to the error:
https://www.loom.com/share/9da68f42ddd44adaad9f987c4fd76baa?sid=8a01b94e-e8fe-499b-b7f4-8d957382194e

**Comment by lwaldron** [comment]
Still seeing this error.

**Comment by tosfos** [comment]
checking

**Comment by tosfos** [comment]
We traced this to a bug that happens when there is a deleted page on your watchlist. I have a hunch on which extension is causing the problem. We'll follow up as soon as we catch the culprit.

**Comment by tosfos** [comment]
It looks like this is a bug in the Echo extension. We have a patch waiting for review. Can you please check if this is fixed?

**Comment by lwaldron** [comment]
Yes looks fixed.
